# Site settings
title: Paula A. Freitas
description: Estudante de Licenciatura em Matemática
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Paula Freitas
user_description: Eu sou estudante de Licenciatura em Matemática.
email: paula.a.freitas@ufv.br

github_username: paulaallves

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
