title : Wall-E - Jekyll
description: 'O Que Está Acontecendo Nesse Gráfico?'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
