# Site settings
title: Graduação MAF
description: Estudante de Licenciatura em Matemática
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Graduação - Licenciatura em Matemática
user_description: "Meu nome é Paula Freitas, sou estudante de Licenciatura em Matemática na UFV Campus Florestal.Esse site tem o intuito de apresentar o corpo docente do curso de matematica na universidade.""
email:



# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
